### ISSUE TITLE
"something went wrong..."

### ISSUE THREAD

**Issue by Daaaaad** [mvgucht/prestashop-DPD_Carrier#1]
I'm testing the module and I get this error message on PS 1.6.0.5 after typing my city :(

![capture d ecran 2015-03-17 a 16 29 27](https://cloud.githubusercontent.com/assets/167037/6690792/cee3e362-ccc2-11e4-9b0f-893a1abee075.png)

**Comment by mvgucht** [comment]
Did you ask IT CS to activate your web service account?

**Comment by Daaaaad** [comment]
No indeed... where did you mention that ?

**Comment by mvgucht** [comment]
I thought it was mentioned in the manual I sent.

I forwarded  your mail to IT -Cs.

**Comment by Daaaaad** [comment]
My bad that's mentioned "Delicom Web Service account has to be active"...
