### ISSUE TITLE
Installation bug on PS 1.5.4.0

### ISSUE THREAD

**Issue by Daaaaad** [mvgucht/prestashop-DPD_Carrier#3]
Hi Michiel,

The webservice has been activated... now I get this error message after installing the module :(

![capture d ecran 2015-05-07 a 13 41 57](https://cloud.githubusercontent.com/assets/167037/7514575/e07bd5fc-f4be-11e4-8abb-899d4188f75f.png)

**Comment by Daaaaad** [comment]
And then if I try to save the parameters... I assume that the two problems are linked.

![capture d ecran 2015-05-07 a 13 49 13](https://cloud.githubusercontent.com/assets/167037/7514673/e8c327f0-f4bf-11e4-86e1-64ff5347ff4f.png)

**Comment by mvgucht** [comment]
Hey David,

this has to do with the initialisation of our 3 shipping methods. But I don't understand how that could go wrong ... it takes the max_weight that is set in the shippingmethods class and if it isn't set it uses the default max_weight.

the first notification states that there is something wrong with the for each loop to...

can you please verify if you have the dpdshippingmethods.php file in your /modules/dpdcarrier/classes/DPD folder?

**Comment by mvgucht** [comment]
Yes, the problems are linked, the carriers failed to initialize so the parameters can't be updated.

**Comment by Daaaaad** [comment]
Yes I have : http://cl.ly/image/2r2P2y2i1w12

**Comment by mvgucht** [comment]
It seems that the class isn't being loaded. are you on a test server? can I have a look?

**Comment by Daaaaad** [comment]
Line 413 is `foreach($method->zones as $zone_name)` and first method don't have a "zones" variable : 

```
$this->methods[0] = new stdClass();
$this->methods[0]->name = 'Home';
$this->methods[0]->type = 'B2B';
$this->methods[0]->description = 'Get your parcel delivered at your place';
```

**Comment by Daaaaad** [comment]
I'm on a test environment yes but I don't manage it myself so it is not easy to give you access...

**Comment by mvgucht** [comment]
Hey David, 

you are right, it should be tested and if needed the default shipping setting should be used.

so change it to:

``` php
$zones = isset($method->zones) ? $method->zones : $default->zones;
foreach($zones as $zone_name)
    $carrier->addZone(Zone::getIdByName($zone_name));
```

**Comment by Daaaaad** [comment]
Grrr I always get the `Property Carrier->max_weight is not valid` error message :(

**Comment by mvgucht** [comment]
Ok, but the foreach error message is now gone? (one step at a time :))

**Comment by Daaaaad** [comment]
Yes it's gone :)

**Comment by mvgucht** [comment]
it seems it is not a problem limited to our module:

https://www.prestashop.com/forums/topic/253464-property-carrier-max-weight-is-not-valid/

I propose you test to be sure by setting all the max_weight to 0 by doing this:
max_weight = 0;

``` php
    $carrier->max_depth = (isset($method->max_width) ? $method->max_width : $default->max_width) * $dimension_multiplier;
    $carrier->max_weight = 0; //(isset($method->max_weight) ? $method->max_weight : $default->max_weight) * $weight_multiplier;
    $carrier->grade = 9;
```

**Comment by Daaaaad** [comment]
id_carrier should not be 0...

![capture d ecran 2015-05-07 a 15 23 27](https://cloud.githubusercontent.com/assets/167037/7516102/0bf291e0-f4cd-11e4-9e0d-614ca64c353f.png)

**Comment by Daaaaad** [comment]
Maybe I should give you the FTP information... I don't have a lot of time for debugging the module :(

**Comment by mvgucht** [comment]
Hey David,

i'm still nog sure it is the modules fault. It creates a new carrier, so that new carrier should get a new id ...

``` php
    {
        $carrier = new Carrier();
        $carrier->name = $method->name;
```

but to be sure you can embed the addZone function after the $carrier->add call:

``` php
    $carrier->grade = 9;

    foreach ($languages as $language) 
        $carrier->delay[$language['id_lang']] = $method->description;

    if (!$carrier->add())
        return false;
    else
    {
        $zones = isset($method->zones) ? $method->zones : $default->zones;
        foreach($zones as $zone_name)
            $carrier->addZone(Zone::getIdByName($zone_name));
```

I can always have a look on your test server if you want. But do email the details directly :)

**Comment by Daaaaad** [comment]
I tested this code : 

![capture d ecran 2015-05-07 a 15 44 45](https://cloud.githubusercontent.com/assets/167037/7516484/03caadec-f4d0-11e4-98d6-7381897c5049.png)

and got this error message : 

![capture d ecran 2015-05-07 a 15 43 20](https://cloud.githubusercontent.com/assets/167037/7516471/e348b53c-f4cf-11e4-8b3c-a43455dff1f7.png)

**Comment by mvgucht** [comment]
Hey David,

can you remove these lines all together:

``` php
    $zones = isset($method->zones) ? $method->zones : $default->zones;
    foreach($zones as $zone_name)
        $carrier->addZone(Zone::getIdByName($zone_name));
```

it seems that a bit lower the code was already corrected but i forgot to remove the initial code:

``` php
$zones = (isset($method->zones) ? $method->zones : $default->zones);

foreach($zones as $zone_name)
{
    $zone = new Zone(Zone::getIdByName($zone_name));
    Db::getInstance()->autoExecute(_DB_PREFIX_ . 'carrier_zone',
        array('id_carrier' => (int) $carrier->id, 'id_zone' => (int) $zone->id), 'INSERT');
    foreach($ranges as $range)
    {
    Db::getInstance()->autoExecuteWithNullValues(_DB_PREFIX_ . 'delivery',
        array('id_carrier' => $carrier->id, 'id_range_price' => NULL, 'id_range_weight' => (int) $range->id, 'id_zone' => (int) $zone->id, 'price' => '0'), 'INSERT');
    }
```

**Comment by Daaaaad** [comment]
Yeah, the module seems to be installed but I get The `PHP SOAP extension not installed/enabled on this server.` error message... can you explain ?

**Comment by mvgucht** [comment]
That's something else :)
you need the php-soap class installed and enabled on your server.

installed with for example apt-get install php_soap (or php5_soap)
and enabled in the php.ini file: (uncomment) extension=soap.so (on Linux I thought) and extension=php_soap.dll on windows.

but if you ask your provider to enable that for you they should know what to do.

the soap service is used to connect to our web server and get the parcelshop information and labels back.

I'll close this issue now because this installation bug has been resolved thanks to your help.

**Comment by Daaaaad** [comment]
Ok I'll ask to our provider but... Is this extension installed by default on common shared/vps hosting ? 

That's important because we sometimes don't have the choice :(

**Comment by mvgucht** [comment]
It is a quite well know web service setup, so most of the time it is installed but just not enabled.
