### ISSUE TITLE
Parcelshop locator does not appear

### ISSUE THREAD

**Issue by Daaaaad** [mvgucht/prestashop-DPD_Carrier#4]
Here is the error message I get :

![capture d ecran 2015-05-12 a 15 45 21](https://cloud.githubusercontent.com/assets/167037/7588516/f4bfd178-f8bd-11e4-848e-a297aee3e3af.png)

**Comment by mvgucht** [comment]
Are you using another extension that uses google maps api? 
This error occurs mostly because the google api isn't correctly loaded in the header.

**Comment by Daaaaad** [comment]
Ok, that was because of a parameter I added to the script's url force cash refresh...

**Comment by mvgucht** [comment]
So I can close this issue?

**Comment by Daaaaad** [comment]
Yes thank you ;)
