### ISSUE TITLE
choiceButton not working

### ISSUE THREAD

**Issue by Daaaaad** [mvgucht/prestashop-DPD_Carrier#6]
When I click on the "choiceButton" nothing happens :(

![capture d ecran 2015-05-12 a 17 01 25](https://cloud.githubusercontent.com/assets/167037/7590399/a239d290-f8c8-11e4-8fbd-39633e7f54cb.png)

**Comment by mvgucht** [comment]
Clicking that button should lauch an ajax call to the selectparcelshop.php controller.
if the connection fails there should be an error message, so I guess the call isn't made.

anything in the console output?

**Comment by Daaaaad** [comment]
Nothing in the console... method "dpdChosenShop" is called but the success callback is not executed.

![capture d ecran 2015-05-19 a 11 44 39](https://cloud.githubusercontent.com/assets/167037/7700091/8d959ac8-fe1c-11e4-9401-0ff35c6a60a1.png)

**Comment by mvgucht** [comment]
ok, ... 
1. are you sure the permissions for the controler are ok? (it should, otherwise you should get an error in the console)
2. you could try to edit the dpdcarrier.js with error function:

``` js
        ,success: function(json) {
            if(json.hasErrors){
                alert(json.errors);
            } else {
                dpdLocator.hideLocator();
                $('#chosenShop').html(json.result);
                if($('#opc_payment_methods')){
                    enableOpcPayment();
                }
            }
        }
        ,error: function(jqXHR, textStatus, errorThrown) {
            alert(textStatus + ": " + errorThrown);
        }
```

this should throw a time out or other issue.

**Comment by Daaaaad** [comment]
Here is the error :

![capture d ecran 2015-05-19 a 14 43 21](https://cloud.githubusercontent.com/assets/167037/7703086/7c7706c8-fe35-11e4-97c4-a37e6ca5818b.png)

**Comment by mvgucht** [comment]
CentOS? :)

try editing parcelhsopselected.php

``` php
class DpdCarrierParcelShopSelectedModuleFrontController extends ModuleFrontController
{       
    public function init()
    {   
        parent::init();
        $referer_url = $_SERVER['HTTP_REFERER'];

        $parsed_referer_url = parse_url($referer_url);
        $base_url = parse_url(_PS_BASE_URL_);

        if(!(isset($_SERVER['HTTP_REFERER'])
            || $parsed_referer_url['host'] == $base_url['host']))
        {
```

**Comment by Daaaaad** [comment]
That works! Thank you

**Comment by mvgucht** [comment]
No problem, don't forget to remove the error function from dpdcarrier.js, we don't want to bother clients with that data.

**Comment by Daaaaad** [comment]
Ok, but maybe you should write something in the console... no ?

**Comment by mvgucht** [comment]
This was a syntax error for you php installation, those errors are best kept away from view.
A time out or server error will show in the console (I tested it befor i added the code)
