### ISSUE TITLE
Parcelshops displayed

### ISSUE THREAD

**Issue by Daaaaad** [mvgucht/prestashop-DPD_Carrier#8]
I think you limit the parcelshops displayed to a delimited zone... What will happen if the visitor decide to navigate into the map with the mouse ? He will not see any parcelshops and deduce that they are no parcelshops in this area... no ?

![capture d ecran 2015-05-19 a 15 49 33](https://cloud.githubusercontent.com/assets/167037/7704454/ab603ece-fe3e-11e4-970c-61f6fae0b7f0.png)

**Comment by mvgucht** [comment]
The web services that we use do not react fine to batch updates, so at this point we choose to only display 10 shops directly around the address the customer entered. If he uses the searchbar to look for an other address the shops will be updated.

**Comment by Daaaaad** [comment]
I think some users will not understand this behavior and will think (in this example) that there are no parcelshops outside of Liège :(

**Comment by mvgucht** [comment]
You can augment the limit here:
https://github.com/DPDBeNeLux/prestashop-DPD_Carrier/blob/master/dpdcarrier/classes/DPD/dpdparcelshopfinder.php#L39

but please note that it is an synchronous call to the controller and that a high number may result in a slow checkout.
