### ISSUE TITLE
carrierInit() - Property Carrier->delay is empty

### ISSUE THREAD

**Issue by GrafykDesign** [mvgucht/prestashop-DPD_Carrier#9]
Hello,

I have just installed it for one of my belgian customer as I'm a web-agency installed in France.
The module is sending an error message while I try to configurate it in the back-office
I fill the inputs. Try to save. And then get this error message : 

---

Prestashop : 1.6.1.4

---

[PrestaShopException]

Property Carrier->delay is empty
at line 954 in file classes/ObjectModel.php
1.                 }
2. 
3.                 $message = $this->validateField($field, $value, $id_lang);
4.                 if ($message !== true) {
5.                     if ($die) {
6.                         throw new PrestaShopException($message);
7.                     }
8.                     return $error_return ? $message : false;
9.                 }
10.             }
11.         }
    ObjectModelCore->validateFieldsLang - [line 295 - classes/ObjectModel.php]
    ObjectModelCore->getFieldsLang - [line 688 - classes/ObjectModel.php]
    ObjectModelCore->update - [line 445 - classes/ObjectModel.php] - [1 Arguments]
    ObjectModelCore->save - [line 140 - modules/dpdcarrier/dpdcarrier.php]
    DpdCarrier->getContent - [line 867 - controllers/admin/AdminModulesController.php]
    AdminModulesControllerCore->postProcessCallback - [line 1116 - controllers/admin/AdminModulesController.php]
    AdminModulesControllerCore->postProcess - [line 178 - classes/controller/Controller.php]
    ControllerCore->run - [line 367 - classes/Dispatcher.php]
    DispatcherCore->dispatch - [line 58 - admin/index.php]

---

**Comment by mvgucht** [comment]
This error can only arise when there are no languages set for the prestashop installation because the initCarrier loads every language that is active on this line:
https://github.com/DPDBeNeLux/prestashop-DPD_Carrier/blob/master/dpdcarrier/dpdcarrier.php#L392

and for each returned language it sets the same description:
https://github.com/DPDBeNeLux/prestashop-DPD_Carrier/blob/master/dpdcarrier/dpdcarrier.php#L420

please try to get the value of line 392 on you system.

**Comment by GrafykDesign** [comment]
It seems it works with the last version of your module.
also.
the default alnguage is french.

Thanks for your help
Regards.

WWW.GRAFYKDESIGN.FR

Arno BERTIN
6 Boulevard Carpeaux - B32
59300 Valenciennes
Fixe : 03 27 40 17 86
Mob : 06 17 25 12 82

---

Horaires d'ouveture : 8h30 à 12h30 & 13h00 à 18h30,
Du lundi au vendredi.

**Comment by mvgucht** [comment]
do you mean that the problem no longer persists?
can I close the ticket then?

**Comment by GrafykDesign** [comment]
Yes you can.

the probelm exists with 0.9 version.
It’s solved with the last version.

WWW.GRAFYKDESIGN.FR

Arno BERTIN
6 Boulevard Carpeaux - B32
59300 Valenciennes
Fixe : 03 27 40 17 86
Mob : 06 17 25 12 82

---

Horaires d'ouveture : 8h30 à 12h30 & 13h00 à 18h30,
Du lundi au vendredi.
